{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e36c8a9c-9a21-4a8d-9155-1992138e7a7d",
   "metadata": {},
   "outputs": [],
   "source": [
    "WHERE NOT (\n",
    "    message LIKE 'Secondary Fallback: Video is playing normally. Current Position:%'\n",
    "    OR message LIKE 'Adjust time zone, response from%'\n",
    "    OR message LIKE 'All files count is%'\n",
    "    OR message LIKE 'Asset byte length%'\n",
    "    OR message LIKE 'Current time is%'\n",
    "    OR message LIKE 'Downloading content %'\n",
    "    OR message LIKE 'getMemoryInfo Available Memory%'\n",
    "    OR message LIKE 'getMemoryInfo Runtime Free Memory%'\n",
    "    OR message LIKE 'getMemoryInfo Runtime Total Memory%'\n",
    "    OR message LIKE 'Item publication date%'\n",
    "    OR message LIKE 'Preloading Next Image Item%'\n",
    "    OR message LIKE 'Received info about current video%'\n",
    "    OR message LIKE 'Remote last-modified%'\n",
    "    OR message LIKE 'Remove unused file%'\n",
    "    OR message LIKE 'Resume download%'\n",
    "    OR message LIKE 'Showing Video Item%'\n",
    "    OR message LIKE 'Showing Image Item%'\n",
    "    OR message LIKE 'Start to download content data to temporary file%'\n",
    "    OR message LIKE 'Start to process content%'\n",
    "    OR message LIKE 'Starting to save content from %'\n",
    "    OR message LIKE 'Starting to Create Thumbnail for%'\n",
    "    OR message LIKE 'Temporary file was renamed successfully %'\n",
    "    OR message LIKE 'Uploading log to S3%'\n",
    "    OR message LIKE 'Used files count is%'\n",
    "    OR message LIKE '%UploadLogs started%'\n",
    "    OR message LIKE '%UploadLogs finished%'\n",
    "    OR message LIKE '%Unable to satisfy @org.simpleframework.xml.ElementList%'\n",
    "    OR message LIKE '%Unable to resolve host%'\n",
    "    OR message LIKE '%TotalRequests%'\n",
    "    OR message LIKE '%create thumbnail%'\n",
    "    OR message LIKE '%Stopped%'\n",
    "    OR message LIKE '%Started%'\n",
    "    OR message LIKE '%Start to clear unused files%'\n",
    "    OR message LIKE '%Start Reboot Thread%'\n",
    "    OR message LIKE '%Received Reboot Broadcast%'\n",
    "    OR message LIKE '%Read timed out%'\n",
    "    OR message LIKE '%Reboot is enabled%'\n",
    "    OR message LIKE '%Read timed out%'\n",
    "    OR message LIKE '%Ping to 8.8.8.8%'\n",
    "    OR message LIKE '%Local file is older than pub date or remote%'\n",
    "    OR message LIKE '%java.net.SocketTimeoutException%'\n",
    "    OR message LIKE '%java.lang.NullPointerException%'\n",
    "    OR message LIKE '%Invalid/missing Content-Length header%'\n",
    "    OR message LIKE '%Internet Status%'\n",
    "    OR message LIKE '%HttpHelper%'\n",
    "    OR message LIKE '%Finish download of content%'\n",
    "    OR message LIKE '%getting location and timzone%'\n",
    "    OR message LIKE '%Failed to get head request%'\n",
    "    OR message LIKE '%End of Broadcast Receiver%'\n",
    "    OR message LIKE '%Using cached data%'\n",
    "    OR message LIKE 'com.bitshuttle.network.RequestException%'\n",
    "    OR message LIKE 'Attempt to invoke virtual method%'\n",
    "    OR message LIKE 'java.lang.NullPointerException%'\n",
    "    OR message LIKE '%getting location and timzone%'\n",
    "    OR message LIKE '%java.net.SocketTimeoutException%'\n",
    "    OR message LIKE '%com.bitshuttle.network.RequestException%'\n",
    "    OR message LIKE '%org.apache.http.conn.ConnectTimeoutException%'\n",
    "    OR message LIKE '%Connect to%'\n",
    "    OR message LIKE '%HttpHelper Statistics%'\n",
    "    OR message LIKE '2023%'\n",
    "    OR message LIKE 'Invalid/missing Content%'\n",
    "    OR message LIKE 'Attempt to invoke virtual method%'\n",
    "    OR message LIKE 'Finish download of%'\n",
    "    OR message LIKE 'Failed asset HEAD request%'\n",
    "    OR message LIKE 'Content data didn%'\n",
    "    OR message LIKE 'Attempt to invoke a%'\n",
    "    OR message LIKE 'Finished processing%'\n",
    "    OR message LIKE '%data loaded%'\n",
    "    OR message LIKE '%ReadRssContentThread%'\n",
    "    OR message LIKE '%RSS loaded%'\n",
    ");\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
